import { useI18n } from '../../contexts/I18nContext';

/**
 * Copy for this module.
 *
 * Held locally rather than in the global I18nContext dictionary: the module
 * ships separately, so its strings travel with it. Falls back to English when
 * an Arabic key is missing.
 */
const copy = {
  en: {
    'brand.name': 'String',
    'brand.tagline': 'The operating system for schools.',

    'back': 'Back to dashboard',
    'title': 'Welcome back',
    'subtitle': 'Sign in to pick up where you left off.',

    'tab.email': 'Email',
    'tab.qr': 'Scan QR',

    'label.email': 'Email or Student ID',
    'ph.email': 'name@string.education',
    'label.password': 'Password',
    'ph.password': 'Enter password',
    'forgot': 'Forgot?',
    'show': 'Show password',
    'hide': 'Hide password',

    'qr.title': 'Point your camera at the screen',
    'qr.hint': 'Your teacher can display a sign-in code. It refreshes every 5 minutes.',

    'cta.login': 'Log in',
    'cta.scan': 'Open scanner',

    'new': 'New to String?',
    'register': 'Register',

    'err.email': 'Enter your email or student ID.',
    'err.password': 'Enter your password.',
    'notice.notWired': 'Interface only — authentication is not connected yet.',

    'pitch.title': 'Everything your class needs, in one place.',
    'pitch.body':
      'One sign-in for your lessons, your class, and your progress — on any device you pick up.',
    'pitch.badge': 'Built for classrooms',

    'nav.dashboard': 'Dashboard',
    'nav.spaces': 'Spaces',
    'rec.start': 'Record',
    'rec.stop': 'Stop recording',
    'nav.members': 'Members',
    'nav.calendar': 'Calendar',
    'nav.grading': 'Grading',
    'nav.chat': 'Chat',
    'nav.ai': 'Aware AI',
    'nav.help': 'Help',
    'nav.menu': 'Open menu',
    'nav.close': 'Close menu',

    'top.notifications': 'Notifications',
    'top.messages': 'Messages',

    'spaces.title': 'Spaces',
    'spaces.subtitle': 'Every class you teach or belong to, in one place.',
    'spaces.search': 'Search spaces, teachers, sections',
    'spaces.count': 'spaces',
    'spaces.empty.title': 'Nothing here yet',
    'spaces.empty.body': 'No space matches this search or filter. Try a different term.',

    'filter.all': 'All',
    'filter.mine': 'Mine',
    'filter.archived': 'Archived',

    'space.members': 'members',
    'space.open': 'Open',
    'space.noNext': 'No session scheduled',
    'space.grade': 'Grade',
    'space.lessonsCount': 'lessons',
    'space.back': 'All spaces',
    'space.lessons': 'Lessons',
    'space.missing.title': 'Space not found',
    'space.missing.body': 'This space does not exist, or you no longer have access to it.',
    'unit.lessons': 'lessons',
    'item.draft': 'Draft',
    'lesson.back': 'Back to space',
    'lesson.missing': 'Lesson not found',
    'artifacts.title': 'Artifacts',
    'artifacts.hint': 'Select a tool to start',
    'art.close': 'Close',
    'str.back': 'All strings',
    'str.none': 'No strings built for this lesson yet.',
    'str.noData': 'This lesson lacks the content this string needs.',
    'str.matchHint': 'Pick a term, then its definition.',
    'str.done': 'All matched!',
    'str.tries': 'Attempts',
    'str.accuracy': 'Accuracy',
    'str.again': 'Play again',
    'str.start': 'Start',
    'str.speedTitle': 'Speed Round',
    'str.speedHint': '{n} questions in 60 seconds. Ready?',
    'str.timeLeft': 'Time left',
    'str.sec': 's',
    'art.openTab': 'Open in a new tab',
    'art.noPdf': 'No textbook file for this unit.',
    'mm.root': 'Main idea',
    'mm.level': 'Level',
    'mm.branches': 'branches',
    'mm.noDetails': 'No description for this node.',
    'mm.pick': 'Select a node to see its description.',
    'mm.zoomIn': 'Zoom in',
    'mm.zoomOut': 'Zoom out',
    'mm.zoomReset': 'Reset zoom',
    'art.empty': 'Nothing generated for this lesson yet.',
    'art.none': 'This lesson has no generated content yet.',
    'art.keyPoints': 'Key points',
    'art.question': 'Question',
    'art.answer': 'Answer',
    'art.reveal': 'Tap to reveal',
    'art.showQuestion': 'Back to question',
    'art.shuffle': 'Shuffle',
    'art.hint': 'Show hint',
    'ws.check': 'Check answers',
    'ws.reset': 'Try again',
    'ws.score': 'Score',
    'ws.choose': 'Choose…',
    'ws.position': 'Order',
    'ws.yourAnswer': 'Your answer',
    'ws.correctAnswer': 'Correct',
    'ws.modelAnswer': 'Model answer',
    'ws.ungraded': 'Discussed with the teacher — not auto-marked.',
    'ws.true': 'True',
    'ws.false': 'False',
    'ws.multiple_choice': 'Choose the correct answer',
    'ws.true_false': 'True or false',
    'ws.match': 'Match the pairs',
    'ws.fill_blank': 'Fill in the blank',
    'ws.classify': 'Classify',
    'ws.sequence': 'Put in order',
    'ws.compare': 'Compare',
    'ws.explain': 'Explain',
    'ws.short_answer': 'Short answer',
    'space.attendance': 'Attendance',
    'att.present': 'Present',
    'att.absent': 'Absent',
    'att.late': 'Late',
    'att.today': 'Today',
    'att.prevDay': 'Previous day',
    'att.nextDay': 'Next day',
    'att.board': 'Board',
    'att.tapHint': 'Tap a seat to change status',
    'att.allPresent': 'Mark all present',
    'att.notSaved': 'Marks are held on this device only — saving is not connected yet.',

    'tool.select': 'Select',
    'tool.pen': 'Pen',
    'tool.highlighter': 'Highlighter',
    'tool.eraser': 'Eraser',
    'tool.shapes': 'Shapes',
    'tool.text': 'Text',
    'tool.note': 'Note',

    'lang': 'العربية',
  },
  ar: {
    'brand.name': 'سترينغ',
    'brand.tagline': 'نظام التشغيل للمدارس.',

    'back': 'العودة للوحة المعلومات',
    'title': 'مرحباً بعودتك',
    'subtitle': 'سجّل الدخول لتكمل من حيث توقفت.',

    'tab.email': 'البريد',
    'tab.qr': 'مسح الرمز',

    'label.email': 'البريد الإلكتروني أو رقم الطالب',
    'ph.email': 'name@string.education',
    'label.password': 'كلمة المرور',
    'ph.password': 'أدخل كلمة المرور',
    'forgot': 'نسيتها؟',
    'show': 'إظهار كلمة المرور',
    'hide': 'إخفاء كلمة المرور',

    'qr.title': 'وجّه الكاميرا نحو الشاشة',
    'qr.hint': 'يمكن لمعلمك عرض رمز الدخول، ويتجدد كل ٥ دقائق.',

    'cta.login': 'تسجيل الدخول',
    'cta.scan': 'افتح الماسح',

    'new': 'جديد على سترينغ؟',
    'register': 'أنشئ حساباً',

    'err.email': 'أدخل بريدك أو رقم الطالب.',
    'err.password': 'أدخل كلمة المرور.',
    'notice.notWired': 'واجهة فقط — لم يتم ربط تسجيل الدخول بعد.',

    'pitch.title': 'كل ما يحتاجه صفك، في مكان واحد.',
    'pitch.body':
      'تسجيل دخول واحد لدروسك وصفك وتقدّمك — على أي جهاز تستخدمه.',
    'pitch.badge': 'مصمّمة للصفوف',

    'nav.dashboard': 'لوحة المعلومات',
    'nav.spaces': 'المساحات',
    'rec.start': 'تسجيل',
    'rec.stop': 'إيقاف التسجيل',
    'nav.members': 'الأعضاء',
    'nav.calendar': 'التقويم',
    'nav.grading': 'الدرجات',
    'nav.chat': 'المحادثة',
    'nav.ai': 'مساعد أوير',
    'nav.help': 'المساعدة',
    'nav.menu': 'افتح القائمة',
    'nav.close': 'أغلق القائمة',

    'top.notifications': 'الإشعارات',
    'top.messages': 'الرسائل',

    'spaces.title': 'المساحات',
    'spaces.subtitle': 'كل صف تدرّسه أو تنتمي إليه، في مكان واحد.',
    'spaces.search': 'ابحث في المساحات والمعلمين والشعب',
    'spaces.count': 'مساحة',
    'spaces.empty.title': 'لا شيء هنا بعد',
    'spaces.empty.body': 'لا توجد مساحة تطابق هذا البحث أو التصفية. جرّب كلمة أخرى.',

    'filter.all': 'الكل',
    'filter.mine': 'مساحاتي',
    'filter.archived': 'المؤرشفة',

    'space.members': 'عضواً',
    'space.open': 'افتح',
    'space.noNext': 'لا حصة مجدولة',
    'space.grade': 'الصف',
    'space.lessonsCount': 'درساً',
    'space.back': 'كل المساحات',
    'space.lessons': 'الدروس',
    'space.missing.title': 'المساحة غير موجودة',
    'space.missing.body': 'هذه المساحة غير موجودة، أو لم يعد لديك صلاحية الوصول إليها.',
    'unit.lessons': 'درساً',
    'item.draft': 'مسودة',
    'lesson.back': 'العودة للمساحة',
    'lesson.missing': 'الدرس غير موجود',
    'artifacts.title': 'المخرجات',
    'artifacts.hint': 'اختر أداة للبدء',
    'art.close': 'إغلاق',
    'str.back': 'كل السترينغز',
    'str.none': 'لا توجد سترينغز لهذا الدرس بعد.',
    'str.noData': 'لا يحتوي هذا الدرس على المحتوى الذي يحتاجه هذا السترينغ.',
    'str.matchHint': 'اختر مصطلحاً، ثم تعريفه.',
    'str.done': 'أحسنت! طابقت الجميع',
    'str.tries': 'المحاولات',
    'str.accuracy': 'الدقة',
    'str.again': 'العب مجدداً',
    'str.start': 'ابدأ',
    'str.speedTitle': 'الجولة السريعة',
    'str.speedHint': '{n} أسئلة في ٦٠ ثانية. جاهز؟',
    'str.timeLeft': 'الوقت المتبقي',
    'str.sec': 'ث',
    'art.openTab': 'افتح في تبويب جديد',
    'art.noPdf': 'لا يوجد ملف كتاب لهذه الوحدة.',
    'mm.root': 'الفكرة الرئيسة',
    'mm.level': 'المستوى',
    'mm.branches': 'فرعاً',
    'mm.noDetails': 'لا يوجد وصف لهذه العقدة.',
    'mm.pick': 'اختر عقدة لعرض وصفها.',
    'mm.zoomIn': 'تكبير',
    'mm.zoomOut': 'تصغير',
    'mm.zoomReset': 'إعادة الحجم',
    'art.empty': 'لا يوجد محتوى مولّد لهذا الدرس بعد.',
    'art.none': 'لا يوجد محتوى مولّد لهذا الدرس بعد.',
    'art.keyPoints': 'النقاط الرئيسة',
    'art.question': 'السؤال',
    'art.answer': 'الإجابة',
    'art.reveal': 'انقر لإظهار الإجابة',
    'art.showQuestion': 'العودة للسؤال',
    'art.shuffle': 'خلط البطاقات',
    'art.hint': 'إظهار التلميح',
    'ws.check': 'تحقق من الإجابات',
    'ws.reset': 'إعادة المحاولة',
    'ws.score': 'النتيجة',
    'ws.choose': 'اختر…',
    'ws.position': 'الترتيب',
    'ws.yourAnswer': 'إجابتك',
    'ws.correctAnswer': 'الصحيح',
    'ws.modelAnswer': 'إجابة نموذجية',
    'ws.ungraded': 'تُناقش مع المعلم — لا تُصحّح تلقائياً.',
    'ws.true': 'صح',
    'ws.false': 'خطأ',
    'ws.multiple_choice': 'اختر الإجابة الصحيحة',
    'ws.true_false': 'صح أم خطأ',
    'ws.match': 'صل بين العمودين',
    'ws.fill_blank': 'أكمل الفراغ',
    'ws.classify': 'صنّف',
    'ws.sequence': 'رتّب',
    'ws.compare': 'قارن',
    'ws.explain': 'وضّح',
    'ws.short_answer': 'إجابة قصيرة',
    'space.attendance': 'الحضور',
    'att.present': 'حاضر',
    'att.absent': 'غائب',
    'att.late': 'متأخر',
    'att.today': 'اليوم',
    'att.prevDay': 'اليوم السابق',
    'att.nextDay': 'اليوم التالي',
    'att.board': 'السبورة',
    'att.tapHint': 'انقر المقعد لتغيير الحالة',
    'att.allPresent': 'تعليم الجميع حاضرين',
    'att.notSaved': 'التعليمات محفوظة على هذا الجهاز فقط — لم يتم ربط الحفظ بعد.',

    'tool.select': 'تحديد',
    'tool.pen': 'قلم',
    'tool.highlighter': 'ملوّن',
    'tool.eraser': 'ممحاة',
    'tool.shapes': 'أشكال',
    'tool.text': 'نص',
    'tool.note': 'ملاحظة',

    'lang': 'English',
  },
} as const;

export type BoardCopyKey = keyof (typeof copy)['en'];

/** Returns a translator scoped to this module. */
export function useBoardCopy() {
  const { locale, dir, toggleLocale } = useI18n();
  const t = (key: BoardCopyKey): string =>
    (copy[locale] as Record<string, string>)[key] ?? copy.en[key] ?? key;
  return { t, locale, dir, toggleLocale };
}
