/**
 * One space per subject per grade, generated alongside the curriculum.
 */
import type { LucideIcon } from 'lucide-react';
import { Atom, BookOpen, Brain, Calculator, FlaskConical, Globe2, Landmark, Languages, Lightbulb, MonitorSmartphone, Moon, Mountain, Sigma, TestTube, Wallet } from 'lucide-react';
import type { AccentKey, Bilingual } from '../spaces';

export interface SubjectSpace {
  id: string;
  grade: string;
  name: Bilingual;
  subject: Bilingual;
  Icon: LucideIcon;
  accent: AccentKey;
  lessons: number;
}

export const SUBJECT_SPACES: SubjectSpace[] = [
  {
    id: "g11-biology",
    grade: "11",
    name: { en: "Biology — Grade 11", ar: "احياء — الحادي عشر" },
    subject: { en: "Biology", ar: "احياء" },
    Icon: FlaskConical,
    accent: "teal",
    lessons: 4,
  },
  {
    id: "g11-islamic",
    grade: "11",
    name: { en: "Islamic Education — Grade 11", ar: "اسلامية — الحادي عشر" },
    subject: { en: "Islamic Education", ar: "اسلامية" },
    Icon: Moon,
    accent: "teal",
    lessons: 25,
  },
  {
    id: "g11-english",
    grade: "11",
    name: { en: "English — Grade 11", ar: "انجليزي — الحادي عشر" },
    subject: { en: "English", ar: "انجليزي" },
    Icon: BookOpen,
    accent: "violet",
    lessons: 9,
  },
  {
    id: "g11-jordan-history",
    grade: "11",
    name: { en: "History of Jordan — Grade 11", ar: "تاريخ الاردن — الحادي عشر" },
    subject: { en: "History of Jordan", ar: "تاريخ الاردن" },
    Icon: Landmark,
    accent: "amber",
    lessons: 13,
  },
  {
    id: "g11-financial",
    grade: "11",
    name: { en: "Financial Literacy — Grade 11", ar: "ثقافة مالية — الحادي عشر" },
    subject: { en: "Financial Literacy", ar: "ثقافة مالية" },
    Icon: Wallet,
    accent: "indigo",
    lessons: 8,
  },
  {
    id: "g11-math",
    grade: "11",
    name: { en: "Mathematics — Grade 11", ar: "رياضيات — الحادي عشر" },
    subject: { en: "Mathematics", ar: "رياضيات" },
    Icon: Calculator,
    accent: "cyan",
    lessons: 13,
  },
  {
    id: "g11-arabic",
    grade: "11",
    name: { en: "Arabic — Grade 11", ar: "عربي — الحادي عشر" },
    subject: { en: "Arabic", ar: "عربي" },
    Icon: Languages,
    accent: "pink",
    lessons: 19,
  },
  {
    id: "g11-earth",
    grade: "11",
    name: { en: "Earth Science — Grade 11", ar: "علوم ارض — الحادي عشر" },
    subject: { en: "Earth Science", ar: "علوم ارض" },
    Icon: Mountain,
    accent: "teal",
    lessons: 6,
  },
  {
    id: "g11-physics",
    grade: "11",
    name: { en: "Physics — Grade 11", ar: "فيزياء — الحادي عشر" },
    subject: { en: "Physics", ar: "فيزياء" },
    Icon: Atom,
    accent: "indigo",
    lessons: 6,
  },
  {
    id: "g11-chemistry",
    grade: "11",
    name: { en: "Chemistry — Grade 11", ar: "كيمياء — الحادي عشر" },
    subject: { en: "Chemistry", ar: "كيمياء" },
    Icon: TestTube,
    accent: "pink",
    lessons: 6,
  },
  {
    id: "g12-biology",
    grade: "12",
    name: { en: "Biology — Grade 12", ar: "احياء — الثاني عشر" },
    subject: { en: "Biology", ar: "احياء" },
    Icon: FlaskConical,
    accent: "teal",
    lessons: 11,
  },
  {
    id: "g12-islamic",
    grade: "12",
    name: { en: "Islamic Education — Grade 12", ar: "اسلامية — الثاني عشر" },
    subject: { en: "Islamic Education", ar: "اسلامية" },
    Icon: Moon,
    accent: "teal",
    lessons: 20,
  },
  {
    id: "g12-english",
    grade: "12",
    name: { en: "English — Grade 12", ar: "انجليزي — الثاني عشر" },
    subject: { en: "English", ar: "انجليزي" },
    Icon: BookOpen,
    accent: "violet",
    lessons: 31,
  },
  {
    id: "g12-history",
    grade: "12",
    name: { en: "History — Grade 12", ar: "تاريخ — الثاني عشر" },
    subject: { en: "History", ar: "تاريخ" },
    Icon: Landmark,
    accent: "amber",
    lessons: 20,
  },
  {
    id: "g12-financial",
    grade: "12",
    name: { en: "Financial Literacy — Grade 12", ar: "ثقافة مالية — الثاني عشر" },
    subject: { en: "Financial Literacy", ar: "ثقافة مالية" },
    Icon: Wallet,
    accent: "indigo",
    lessons: 14,
  },
  {
    id: "g12-geography",
    grade: "12",
    name: { en: "Geography — Grade 12", ar: "جغرافيا — الثاني عشر" },
    subject: { en: "Geography", ar: "جغرافيا" },
    Icon: Globe2,
    accent: "indigo",
    lessons: 14,
  },
  {
    id: "g12-math",
    grade: "12",
    name: { en: "Mathematics — Grade 12", ar: "رياضيات — الثاني عشر" },
    subject: { en: "Mathematics", ar: "رياضيات" },
    Icon: Calculator,
    accent: "cyan",
    lessons: 9,
  },
  {
    id: "g12-business-math",
    grade: "12",
    name: { en: "Business Mathematics — Grade 12", ar: "رياضيات اعمال — الثاني عشر" },
    subject: { en: "Business Mathematics", ar: "رياضيات اعمال" },
    Icon: Sigma,
    accent: "cyan",
    lessons: 11,
  },
  {
    id: "g12-arabic",
    grade: "12",
    name: { en: "Arabic — Grade 12", ar: "عربي — الثاني عشر" },
    subject: { en: "Arabic", ar: "عربي" },
    Icon: Languages,
    accent: "pink",
    lessons: 32,
  },
  {
    id: "g12-psychology",
    grade: "12",
    name: { en: "Psychology — Grade 12", ar: "علم النفس — الثاني عشر" },
    subject: { en: "Psychology", ar: "علم النفس" },
    Icon: Brain,
    accent: "violet",
    lessons: 28,
  },
  {
    id: "g12-earth",
    grade: "12",
    name: { en: "Earth Science — Grade 12", ar: "علوم ارض — الثاني عشر" },
    subject: { en: "Earth Science", ar: "علوم ارض" },
    Icon: Mountain,
    accent: "teal",
    lessons: 8,
  },
  {
    id: "g12-philosophy",
    grade: "12",
    name: { en: "Philosophy — Grade 12", ar: "فلسفة — الثاني عشر" },
    subject: { en: "Philosophy", ar: "فلسفة" },
    Icon: Lightbulb,
    accent: "violet",
    lessons: 25,
  },
  {
    id: "g12-physics",
    grade: "12",
    name: { en: "Physics — Grade 12", ar: "فيزياء — الثاني عشر" },
    subject: { en: "Physics", ar: "فيزياء" },
    Icon: Atom,
    accent: "indigo",
    lessons: 11,
  },
  {
    id: "g12-chemistry",
    grade: "12",
    name: { en: "Chemistry — Grade 12", ar: "كيمياء — الثاني عشر" },
    subject: { en: "Chemistry", ar: "كيمياء" },
    Icon: TestTube,
    accent: "pink",
    lessons: 11,
  },
  {
    id: "g12-digital",
    grade: "12",
    name: { en: "Digital Skills — Grade 12", ar: "مهارات رقمية — الثاني عشر" },
    subject: { en: "Digital Skills", ar: "مهارات رقمية" },
    Icon: MonitorSmartphone,
    accent: "cyan",
    lessons: 10,
  },
];
